apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-tj4d
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ypcs-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-tj4d@sha256:d86facf0571abb89979edbc3653f66f10cf7928487247842c0f013a8c7f64d11
        name: my-python
        resources: {}
status: {}
